// Generated by script, please do not edit this file.
import type { SVGProps } from "react";
import { Ref, forwardRef } from "react";
const Ellipse = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
    <svg
        width="1em"
        height="1em"
        ref={ref}
        {...props}
        viewBox="0 0 24 24"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg">
        <path
            d="M12 2.5C18.4405 2.5 23.5 6.83478 23.5 12C23.5 17.1652 18.4405 21.5 12 21.5C5.5595 21.5 0.5 17.1652 0.5 12C0.5 6.83478 5.5595 2.5 12 2.5Z"
            fill="none"
            stroke={props.stroke}
        />
    </svg>
);
const ForwardRef = forwardRef(Ellipse);
export default ForwardRef;
