// Generated by script, please do not edit this file.
import type { SVGProps } from "react";
import { Ref, forwardRef } from "react";
const Rectange = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
    <svg
        width="1em"
        height="1em"
        ref={ref}
        {...props}
        viewBox="0 0 24 24"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg">
        <rect
            x="0.5"
            y="0.5"
            width="23"
            height="23"
            stroke={props.stroke}
            fill="none"
        />
    </svg>
);
const ForwardRef = forwardRef(Rectange);
export default ForwardRef;
