// Generated by script, please do not edit this file.
import type { SVGProps } from "react";
import { Ref, forwardRef } from "react";
const Text = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
    <svg
        width="1em"
        height="1em"
        ref={ref}
        {...props}
        viewBox="0 0 24 24"
        version="1.1"
        xmlns="http://www.w3.org/2000/svg">
        <path
            fillRule="evenodd"
            clipRule="evenodd"
            d="M24 0V7.2H21.6C21.6 4.5492 19.4508 2.4 16.8 2.4H15.1032C14.052 2.4 13.2 3.25193 13.2 4.30313V20.4C13.2 21.0624 13.7376 21.6 14.4 21.6H16.8V24H7.2V21.6H9.6C10.2624 21.6 10.8 21.0624 10.8 20.4V4.30313C10.8 3.25193 9.948 2.4 8.8968 2.4H7.2C4.5492 2.4 2.4 4.5492 2.4 7.2H0V0H24Z"
        />
    </svg>
);
const ForwardRef = forwardRef(Text);
export default ForwardRef;
