// Generated by script, please do not edit this file.
import type { SVGProps } from "react";
import React, { Ref, forwardRef } from "react";
const Distinct = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="1em"
        height="1em"
        ref={ref}
        {...props}
        viewBox="0 0 64 64">
        <path d="M6.06125 4.01758C4.95625 4.01758 4.06125 4.91258 4.06125 6.01758V57.9238L7 54.9851V7.18758C7 7.11883 7.055 7.06258 7.125 7.06258H54.9225L57.9675 4.01758H6.06125Z" />
        <path d="M11 9.95508C10.4475 9.95508 10 10.4026 10 10.9551V51.9851L52.03 9.95508H11ZM16.2175 16.0488V26.9876H13.2175V14.1738C13.2175 13.6213 13.665 13.1738 14.2175 13.1738H27.0313V16.0488H16.2175Z" />
        <path d="M6.2475 59.8924H58.0612C59.1662 59.8924 60.0612 58.9974 60.0612 57.8924V6.07861L6.2475 59.8924ZM56.0612 57.0174H13.2175L57.0612 13.1736V56.0174C57.0612 56.5699 56.6137 57.0174 56.0612 57.0174Z" />
        <path d="M51.0613 40.2036V51.1424H40.2475V54.0174H53.0613C53.6138 54.0174 54.0613 53.5699 54.0613 53.0174V40.2036H51.0613Z" />
    </svg>
);
const ForwardRef = forwardRef(Distinct);
export default ForwardRef;
