// Generated by script, please do not edit this file.
import type { SVGProps } from "react";
import React, { Ref, forwardRef } from "react";
const Select = (props: SVGProps<SVGSVGElement>, ref: Ref<SVGSVGElement>) => (
    <svg
        xmlns="http://www.w3.org/2000/svg"
        width="1em"
        height="1em"
        ref={ref}
        {...props}
        viewBox="0 0 64 64">
        <path d="M46.032 28.5292C46.032 28.0172 45.712 27.5692 45.2 27.3772L19.664 18.0332C19.024 17.7772 18.32 18.0332 18.064 18.6732C17.936 18.9932 17.936 19.3132 18.064 19.6332L27.408 45.1692C27.6 45.6812 28.048 46.0012 28.56 46.0012C28.56 46.0652 28.56 46.0652 28.624 46.0652C29.136 46.0652 29.584 45.7452 29.776 45.2972L34.256 36.1452L40.016 42.2892C40.272 42.5452 40.592 42.6732 40.976 42.6732C41.296 42.6732 41.616 42.5452 41.872 42.2892C42.384 41.8412 42.384 41.0732 41.936 40.5612L41.872 40.4972L36.048 34.3532L45.264 29.8092C45.776 29.4892 46.032 29.0412 46.032 28.5292ZM32.528 33.8412L28.88 41.5212L21.392 21.3612L41.616 28.7852L33.936 32.4332C32.848 33.0092 32.528 33.8412 32.528 33.8412Z" />
    </svg>
);
const ForwardRef = forwardRef(Select);
export default ForwardRef;
