// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import ArrowSvg from "../icons/Arrow";

const Arrow = createSvgIcon({
    as: ArrowSvg,
    ariaLabel: "arrow",
    category: "zc icons",
    displayName: "Arrow",
});

export default Arrow;
