// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import BallSvg from "../icons/Ball";

const Ball = createSvgIcon({
    as: BallSvg,
    ariaLabel: "ball",
    category: "zc icons",
    displayName: "Ball",
});

export default Ball;
