// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import CurvedArrowSvg from "../icons/CurvedArrow";

const CurvedArrow = createSvgIcon({
    as: CurvedArrowSvg,
    ariaLabel: "curved arrow",
    category: "zc icons",
    displayName: "Curved arrow",
});

export default CurvedArrow;
