// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import EllipseSvg from "../icons/Ellipse";

const Ellipse = createSvgIcon({
    as: EllipseSvg,
    ariaLabel: "ellipse",
    category: "zc icons",
    displayName: "Ellipse",
});

export default Ellipse;
