// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import FlagSvg from "../icons/Flag";

const Flag = createSvgIcon({
    as: FlagSvg,
    ariaLabel: "flag",
    category: "zc icons",
    displayName: "Flag",
});

export default Flag;
