// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import FlagWithStandSvg from "../icons/FlagWithStand";

const FlagWithStand = createSvgIcon({
    as: FlagWithStandSvg,
    ariaLabel: "flag with stand",
    category: "zc icons",
    displayName: "Flag with stand",
});

export default FlagWithStand;
