// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import HandSvg from "../icons/Hand";

const Hand = createSvgIcon({
    as: HandSvg,
    ariaLabel: "hand",
    category: "zc icons",
    displayName: "Hand",
});

export default Hand;
