// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import JudgeSvg from "../icons/Judge";

const Judge = createSvgIcon({
    as: JudgeSvg,
    ariaLabel: "judge",
    category: "zc icons",
    displayName: "Judge",
});

export default Judge;
