// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import Player01Svg from "../icons/Player01";

const Player01 = createSvgIcon({
    as: Player01Svg,
    ariaLabel: "player-01",
    category: "zc icons",
    displayName: "Player-01",
});

export default Player01;
