// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import PlayerSvg from "../icons/Player";

const Player = createSvgIcon({
    as: PlayerSvg,
    ariaLabel: "player",
    category: "zc icons",
    displayName: "Player",
});

export default Player;
