// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import RectangleSvg from "../icons/Rectangle";

const Rectangle = createSvgIcon({
    as: RectangleSvg,
    ariaLabel: "rectange",
    category: "zc icons",
    displayName: "Rectangle",
});

export default Rectangle;
