// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import ShapeSvg from "../icons/Shape";

const Shape = createSvgIcon({
    as: ShapeSvg,
    ariaLabel: "shape",
    category: "zc icons",
    displayName: "Shape",
});

export default Shape;
