// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SoccerToolsSvg from "../icons/SoccerTools01";

const SoccerTools01 = createSvgIcon({
    as: SoccerToolsSvg,
    ariaLabel: "soccer tools-01",
    category: "zc icons",
    displayName: "Soccer tools-01",
});

export default SoccerTools01;
