// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SoccerMindSvg from "../icons/SoccerMind";

const SoccerMind = createSvgIcon({
    as: SoccerMindSvg,
    ariaLabel: "soccer mind",
    category: "zc icons",
    displayName: "Soccer Mind",
});

export default SoccerMind;
