// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SoccerFieldSvg from "../icons/SoccerField";

const SoccerField = createSvgIcon({
    as: SoccerFieldSvg,
    ariaLabel: "soccer field",
    category: "zc icons",
    displayName: "Soccer field",
});

export default SoccerField;
