// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SoccerToolsSvg from "../icons/SoccerTools";

const SoccerTools = createSvgIcon({
    as: SoccerToolsSvg,
    ariaLabel: "soccer tools",
    category: "zc icons",
    displayName: "Soccer tools",
});

export default SoccerTools;
