// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import TacticSvg from "../icons/TacticTools";

const TacticTools = createSvgIcon({
    as: TacticSvg,
    ariaLabel: "tactic tools",
    category: "zc icons",
    displayName: "Tactic tools",
});

export default TacticTools;
