// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import TextSvg from "../icons/Text";

const Text = createSvgIcon({
    as: TextSvg,
    ariaLabel: "text",
    category: "zc icons",
    displayName: "Text",
});

export default Text;
