// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import ZoomOutSvg from "../icons/ZoomOut";

const ZoomOut = createSvgIcon({
    as: ZoomOutSvg,
    ariaLabel: "zoom out",
    category: "zc icons",
    displayName: "ZoomOutIcon",
});

export default ZoomOut;
