// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import ZoomInSvg from "../icons/ZoomIn";

const ZoomIn = createSvgIcon({
    as: ZoomInSvg,
    ariaLabel: "zoom in",
    category: "zc icons",
    displayName: "ZoomInIcon",
});

export default ZoomIn;
