// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import AggregationSvg from "../icons/dfl-flow/Aggregation";

const Aggregation = createSvgIcon({
    as: AggregationSvg,
    ariaLabel: "aggregation",
    category: "dfl flow",
    displayName: "Aggregation",
});

export default Aggregation;
