// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import DistinctSvg from "../icons/dfl-flow/Distinct";

const Distinct = createSvgIcon({
    as: DistinctSvg,
    ariaLabel: "distinct",
    category: "dfl flow",
    displayName: "Distinct",
});

export default Distinct;
