// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import DummyTargetSvg from "../icons/dfl-flow/DummyTarget";

const DummyTarget = createSvgIcon({
    as: DummyTargetSvg,
    ariaLabel: "dummy target",
    category: "dfl flow",
    displayName: "DummyTarget",
});

export default DummyTarget;
