// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import DummySourceSvg from "../icons/dfl-flow/DummySource";

const DummySource = createSvgIcon({
    as: DummySourceSvg,
    ariaLabel: "dummy source",
    category: "dfl flow",
    displayName: "DummySource",
});

export default DummySource;
