// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import ExpressionSvg from "../icons/dfl-flow/Expression";

const Expression = createSvgIcon({
    as: ExpressionSvg,
    ariaLabel: "expression",
    category: "dfl flow",
    displayName: "Expression",
});

export default Expression;
