// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import FilterSvg from "../icons/dfl-flow/Filter";

const Filter = createSvgIcon({
    as: FilterSvg,
    ariaLabel: "filter",
    category: "dfl flow",
    displayName: "Filter",
});

export default Filter;
