// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import JoinSvg from "../icons/dfl-flow/Join";

const Join = createSvgIcon({
    as: JoinSvg,
    ariaLabel: "join",
    category: "dfl flow",
    displayName: "Join",
});

export default Join;
