// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import RepartitionSvg from "../icons/dfl-flow/Repartition";

const Repartition = createSvgIcon({
    as: RepartitionSvg,
    ariaLabel: "repartition",
    category: "dfl flow",
    displayName: "Repartition",
});

export default Repartition;
