// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SamplingSvg from "../icons/dfl-flow/Sampling";

const Sampling = createSvgIcon({
    as: SamplingSvg,
    ariaLabel: "sampling",
    category: "dfl flow",
    displayName: "Sampling",
});

export default Sampling;
