// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SelectSvg from "../icons/dfl-flow/Select";

const Select = createSvgIcon({
    as: SelectSvg,
    ariaLabel: "select",
    category: "dfl flow",
    displayName: "Select",
});

export default Select;
