// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SortNodeSvg from "../icons/dfl-flow/SortNode";

const SortNode = createSvgIcon({
    as: SortNodeSvg,
    ariaLabel: "sort node",
    category: "dfl flow",
    displayName: "Sort Node",
});

export default SortNode;
