// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SourceSvg from "../icons/dfl-flow/Source";

const Distinct = createSvgIcon({
    as: SourceSvg,
    ariaLabel: "source",
    category: "dfl flow",
    displayName: "Source",
});

export default Distinct;
