// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SqlSvg from "../icons/dfl-flow/Sql";

const Sql = createSvgIcon({
    as: SqlSvg,
    ariaLabel: "sql node",
    category: "dfl flow",
    displayName: "Sql",
});

export default Sql;
