// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import SubFlowSvg from "../icons/dfl-flow/SubFlow";

const SubFlow = createSvgIcon({
    as: SubFlowSvg,
    ariaLabel: "sub flow",
    category: "dfl flow",
    displayName: "SubFlow",
});

export default SubFlow;
