// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import TargetSvg from "../icons/dfl-flow/Target";

const Target = createSvgIcon({
    as: TargetSvg,
    ariaLabel: "target",
    category: "dfl flow",
    displayName: "Target",
});

export default Target;
