// Generated by script, don't edit it please.
import createSvgIcon from "../createSvgIcon";
import UnionSvg from "../icons/dfl-flow/Union";

const Union = createSvgIcon({
    as: UnionSvg,
    ariaLabel: "union",
    category: "dfl flow",
    displayName: "Union",
});

export default Union;
